# Usar uma imagem base do Nginx para servir arquivos estáticos
FROM nginx:alpine

# Copiar os arquivos do frontend para o diretório padrão do Nginx
COPY . /usr/share/nginx/html

# Expor a porta 80 (padrão do Nginx)
EXPOSE 80
